name: Frontend CI

on:
  push:
    branches: ["main"]
    paths:
    - 'frontend/**'
  pull_request:
    branches: ["main"]
    paths:
    - 'frontend/**'

jobs:
  frontend_ci:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_RUNTIME_ENV: ${{ secrets.NEXT_RUNTIME_ENV }}

    defaults:
      run:
        working-directory: frontend/csquizz-web-app

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/csquizz-web-app/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # not any UT for frontend yet
    # - name: Test
    #   run: npm test